# Generated by Django 6.0.5 on 2026-06-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_routineexercise_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='recently_changed',
            field=models.BooleanField(default=True),
        ),
    ]
