# Generated by Django 6.0.5 on 2026-06-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersettings_smartchange_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='set_carryover',
            field=models.BooleanField(default=True),
        ),
    ]
