# Generated by Django 6.0.5 on 2026-06-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_demo_usersettings_set_carryover'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='accessory_rest_time',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notification_sound_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notification_vibration_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='primary_rest_time',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='secondary_rest_time',
            field=models.IntegerField(default=120),
        ),
    ]
