# Generated by Django 6.0.5 on 2026-08-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usersettings_accessory_rest_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dev',
            field=models.BooleanField(default=False),
        ),
    ]
