# Generated by Django 6.0.5 on 2026-05-25 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('exercise_type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('accessory', 'Accessory')], default='accessory', max_length=20)),
                ('primary_bodypart', models.CharField(blank=True, choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('legs', 'Legs'), ('core', 'Core'), ('cardio', 'Cardio')], help_text='Primary muscle group targeted by this exercise', max_length=20, null=True)),
                ('secondary_bodypart', models.CharField(blank=True, choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('legs', 'Legs'), ('core', 'Core'), ('cardio', 'Cardio')], help_text='Secondary muscle group targeted by this exercise', max_length=20, null=True)),
                ('weight_increment', models.DecimalField(blank=True, decimal_places=1, help_text='Weight increment in kg for this exercise (e.g., 1.0, 2.5)', max_digits=4, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
