# Generated by Django 6.0.5 on 2026-06-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='alternative_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
