# Generated by Django 6.0.5 on 2026-06-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_alternative_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='primary_bodypart',
            field=models.CharField(blank=True, choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('legs', 'Legs'), ('core', 'Core'), ('cardio', 'Cardio'), ('other', 'Other')], help_text='Primary muscle group targeted by this exercise', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='secondary_bodypart',
            field=models.CharField(blank=True, choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('legs', 'Legs'), ('core', 'Core'), ('cardio', 'Cardio'), ('other', 'Other')], help_text='Secondary muscle group targeted by this exercise', max_length=20, null=True),
        ),
    ]
