# Generated by Django 6.0.5 on 2026-08-02 17:38

from django.db import migrations, models


def seed_exercise_metadata(apps, schema_editor):
    from seeding.exercise_metadata import seed_builtin_exercise_metadata

    seed_builtin_exercise_metadata()


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_weight_increment_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='equipment_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='exercise',
            name='movement_kind',
            field=models.CharField(choices=[('compound', 'Compound'), ('isolation', 'Isolation')], default='compound', max_length=20),
        ),
        migrations.RunPython(seed_exercise_metadata, migrations.RunPython.noop),
    ]
