# Generated by Django 6.0.5 on 2026-08-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_exercise_ai_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='push_pull',
            field=models.CharField(choices=[('push', 'Push'), ('pull', 'Pull'), ('na', 'N/A')], default='na', max_length=10),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='primary_bodypart',
            field=models.CharField(blank=True, choices=[('chest', 'Chest'), ('upper_chest', 'Upper chest'), ('lower_chest', 'Lower chest'), ('back', 'Back'), ('lats', 'Lats'), ('traps', 'Traps'), ('lower_back', 'Lower back'), ('shoulders', 'Shoulders'), ('front_delts', 'Front delts'), ('lateral_delts', 'Lateral delts'), ('rear_delts', 'Rear delts'), ('arms', 'Arms'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('legs', 'Legs'), ('quads', 'Quads'), ('glutes', 'Glutes'), ('hamstrings', 'Hamstrings'), ('calves', 'Calves'), ('core', 'Core'), ('abs', 'Abs'), ('obliques', 'Obliques'), ('cardio', 'Cardio'), ('other', 'Other')], help_text='Primary muscle group targeted by this exercise', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='secondary_bodypart',
            field=models.CharField(blank=True, choices=[('chest', 'Chest'), ('upper_chest', 'Upper chest'), ('lower_chest', 'Lower chest'), ('back', 'Back'), ('lats', 'Lats'), ('traps', 'Traps'), ('lower_back', 'Lower back'), ('shoulders', 'Shoulders'), ('front_delts', 'Front delts'), ('lateral_delts', 'Lateral delts'), ('rear_delts', 'Rear delts'), ('arms', 'Arms'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('legs', 'Legs'), ('quads', 'Quads'), ('glutes', 'Glutes'), ('hamstrings', 'Hamstrings'), ('calves', 'Calves'), ('core', 'Core'), ('abs', 'Abs'), ('obliques', 'Obliques'), ('cardio', 'Cardio'), ('other', 'Other')], help_text='Secondary muscle group targeted by this exercise', max_length=20, null=True),
        ),
    ]
