# Generated by Django 6.0.5 on 2026-05-25 10:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('exercise_type', models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('accessory', 'Accessory')], max_length=20, null=True)),
                ('performance_feedback', models.CharField(blank=True, choices=[('increase', 'Increase'), ('stay', 'Stay'), ('decrease', 'Decrease')], max_length=10, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workout')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('reps', models.PositiveIntegerField(default=0)),
                ('is_warmup', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.workoutexercise')),
            ],
            options={
                'ordering': ['set_number'],
            },
        ),
    ]
