# Generated by Django 6.0.5 on 2026-06-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workout_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
