# Generated by Django 6.0.5 on 2026-06-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workoutexercise_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='progression_step',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
