# Generated by Django 6.0.5 on 2026-06-09 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='accessory_carryover',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='program',
            name='last_used_routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='routines.routine'),
        ),
        migrations.AddField(
            model_name='program',
            name='primary_carryover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='secondary_carryover',
            field=models.BooleanField(default=False),
        ),
    ]
