# Generated by Django 6.0.5 on 2026-06-27 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_progressiontemplate_progressionstep'),
        ('routines', '0002_routineexercise_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='accessory_progression_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='programs.progressiontemplate'),
        ),
        migrations.AddField(
            model_name='program',
            name='primary_progression_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='programs.progressiontemplate'),
        ),
        migrations.AddField(
            model_name='program',
            name='secondary_progression_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='programs.progressiontemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='programroutine',
            unique_together={('program', 'routine')},
        ),
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_exercises', to='programs.program')),
                ('progression_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_exercises', to='programs.progressiontemplate')),
                ('routine_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_exercises', to='routines.routineexercise')),
            ],
            options={
                'unique_together': {('program', 'routine_exercise')},
            },
        ),
    ]
