# Generated by Django 6.0.5 on 2026-07-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_no_progression_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='last_used_routine',
        ),
    ]
