# Generated by Django 6.0.5 on 2026-08-20 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(max_length=16)),
                ('url', models.TextField()),
                ('request', models.JSONField(blank=True, null=True)),
                ('response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('exception', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='apis_apical_content_24b886_idx'), models.Index(fields=['created_at'], name='apis_apical_created_118c8a_idx')],
            },
        ),
    ]
