# Generated by Django 6.0.5 on 2026-08-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicall',
            name='response_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
