# Generated by Django 6.0.5 on 2026-09-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aichat_guest_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aichat',
            new_name='ai_aichat_guest_i_27cde4_idx',
            old_name='ai_aichat_guest_i_created_idx',
        ),
    ]
